spring:
  application:
    name: web-server-scaling-stage-03
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_labs_stage03
    username: backend_labs
    password: backend_labs
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
